language: node_js
node_js:
- node
cache: npm
before_install:
- npm install recursive-install
install:
- npm-recursive-install --skip-root
script:
- cd ./client && npm run build
deploy:
  provider: heroku
  skip-cleanup: true
  api_key:
    secure: RZ12N9z5ysetkAxtDlenztKbt/QJ2JqBHCFtYJS9k0Euuh6rRUZNugP721REbR0JFNin/JpZw9EJjluWiKhwye71MclEZYYRf29GPya+bI4+cG6XTwDZ/1o8ojPKG8RQCPxynQSBTCw2c3j7G6WJnvqeQ/UfDxSTxrYVCYbYDFRr+1bDN+/lhpbTGAKXdEjB6+ROhb+zdz3IPaWBv07mxO1BfaMjt9Ah5LuBolE8QTUNODtjsI5kxrdxLqG1CbX2Q4Ut449NsxsDucee8qdjMLcus0G05G7nhO9XiVZb7aDUDBZZy7nA93DWQS41avextqlZR8KsMVbVNfKf8l6yN4sG2JhoXWPWucO1nPseg5YTLR7+2wwy568cPS+ZGcr3BwH1anr8YK7sjhP3zKfKWBK9Nm7dN78g4Ys84xTxcN/ECmIy9TKlQ4JqIkinKrK8sxHrs5ZFynhsLRJYkLHBAcow8gHTHSY0iK5EVxy+EP2npZHZMiWAxDHH/Sb9wrIDMjNKFuD7DMEzduu07aucGpshVROYkiuBcyMthBUotB6OsFu007mFtHpxc0rXav2Yn/SuPksyqbc45kNo+ED7HqSir7LXlu8aoETNZ61bmrD4zyLLW0nXStYY+Wwo7LQdfc5Axd3KsIhNHl0YoJ/beoMcPESe6OurWxvieJwfPaI=
  on:
    branch: master
