language: node_js
node_js:
    - node
cache: npm
before_install:
    - npm install recursive-install
install:
    - npm-recursive-install --skip-root
script:
    - cd ./client && npm run build
deploy:
    provider: heroku
    on:
        branch: master
    api_key: $HEROKU_KEY
