language: node_js
node_js:
- node
cache: npm
before_install:
- npm install recursive-install
install:
- npm-recursive-install --skip-root
script:
- cd ./client && npm run build
deploy:
  provider: heroku
  skip-cleanup: true
  api_key:
    secure: PZYxyoiZY4zATeUlyvOHYCEb3yzutkj+LZBjl2QX8gPiaLBwxfidWV7WkGuKZxNLf1G05lfG6M65CM0w3FXdZiJHrwkJRKyu71iTwn7EqjgBr0YTMqiA4E6vWB24OsZBVHmE8Tkcbtbjv6/Wfi5WFU79LjBMSNsDd+3jpaNyH75Fc/Ut60z7U6y5Ou4UwdoED252paygLGFOuH2+5Q//OKu/JhPaPM2bILOanZJdi8FTGnLrCNRMRfUlwfkBKAF5LqJLEzbsX/QSQnvExCDv+cG9ej0EgULhnGQf4HEWONOsox6N3K/UPtY1DGi2KvElOpbywk8k/64b86RIDNC1rreXopO0Kob6AFlzlTkSfudT1XE0ON4T0uIV6D9YjsVlsxPmVtlCNXNV+Eq6o/Lk4T0Jy/HJ9uKMYkR/N2TxCIeVMdaS/wmS0RlkNaazpMBWQZ+F1GZdMJf48Spno28VmuAtnbCXOjzEi4i1rXYzM2aW/zdaXSagssJOCDn7dmfQOkDq5NJW/1byOD/fj1l2NpnFPjlcuTNydUs3cYLR6Nbu8O1o417O2TRieQPRoMn9JrnKoZjowYsFyDLo1SPtfQnzBVKP2D3yU5iZ29N5z/uPdBKSfHdJTAPVUXIVOTNxVqIA12B77Xrjw+923f8zeRphkqjsN/94GE9ZO8o8Js0=
  on:
    branch: master
