name: "test code style"
on:
    push:
        branches: [master, BackEnd, FrontEnd]
    pull_request:
        branches: [master]
jobs:
    test:
        run-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  version: 12
            - run: cd ./client && npm ci
            - run: cd ./client && npm run test:lint
