name: "test code style"
on:
    push:
        branches: [master, BackEnd, FrontEnd]
    pull_request:
        branches: [master]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  version: 12
            - run: cd ./client &&  echo "current path :$(pwd)" && npm ci && npm run test:lint
            - run: cd ./server &&  echo "current path :$(pwd)" && npm ci && npm run test:lint
